### PR TITLE
Update Plugin.cs

### PR DESCRIPTION
**Pull request by lostone-zc**

### CODE REVIEW

**Comment by crazyjackel** [comment]
Hello, I am going to wait until my 2.0.0 release before doing pull requests. Feel free to submit issues in the mean time prior to creating a pull request. Issues let me know what’s up and what people want solved.

**Comment by lostone-zc** [comment]
Update the request

**Comment by crazyjackel** [comment]
Change the Branch to Develop please. Then I will merge it in and it will be included in the next version release.

**Comment by lostone-zc** [comment]
okay, thanks.

**Pull request merged**
